#!/usr/bin/env python3
import os, subprocess, datetime, time, sys, threading
from colorama import Fore, init
init(autoreset=True)

last_target = "Unknown"

def banner():
    print(Fore.CYAN + """
╔══════════════════════════════════════════════════════════════╗
║     UNROOTED TERMUX BUG BOUNTY ARSENAL v2.9                  ║
║        COMPLETE ALL-IN-ONE BUG BOUNTY TOOLKIT               ║
╚══════════════════════════════════════════════════════════════╝
    """)

# Full Spinner + Filling Progress Bar
def progress_task(stop_event, message, total_time=60):
    spinner = ['|', '/', '-', '\\']
    bar_length = 25
    i = 0
    start = time.time()
    while not stop_event.is_set():
        elapsed = time.time() - start
        progress = min(elapsed / total_time, 1.0)
        filled = int(bar_length * progress)
        bar = '█' * filled + '░' * (bar_length - filled)
        percent = int(progress * 100)
        sys.stdout.write(f"\r{Fore.YELLOW}[{spinner[i % 4]}] {message} | {bar} {percent}% ")
        sys.stdout.flush()
        time.sleep(0.25)
        i += 1
    sys.stdout.write(f"\r{Fore.GREEN}[✓] {message} | {'█' * bar_length} 100% \n")
    sys.stdout.flush()

def run_cmd(cmd, description="", estimated_seconds=60, long_running=False):
    if description:
        print(Fore.MAGENTA + f"[→] {description}")
    print(Fore.YELLOW + f"[+] Running: {cmd}")
    if long_running:
        print(Fore.CYAN + "   ⏳ This may take 5-20+ minutes on mobile...")

    stop_event = threading.Event()
    thread = threading.Thread(target=progress_task, args=(stop_event, description, estimated_seconds))
    thread.start()

    try:
        result = subprocess.run(cmd, shell=True, text=True, capture_output=True)
        stop_event.set()
        thread.join()
        print(Fore.GREEN + "[✓] Completed")
        if result.stdout and len(result.stdout) < 400:
            print(result.stdout.strip()[:300])
        return result.stdout
    except Exception as e:
        stop_event.set()
        thread.join()
        print(Fore.RED + f"Error: {e}")
        return ""

def run_user_tool(tool_path, name):
    print(Fore.MAGENTA + f"[→] Launching {name}...")
    full_path = f"modules/{tool_path}"
    if os.path.exists(full_path):
        subprocess.run(f"python3 {full_path}", shell=True, cwd=os.getcwd())
    else:
        print(Fore.RED + f"Tool not found: {full_path}")

def full_automated_chain():
    global last_target
    target = input("Enter target domain (example.com): ")
    last_target = target
    print(Fore.CYAN + f"🚀 Running FULL AUTOMATED BUG BOUNTY CHAIN for {target}...")

    run_cmd(f"subfinder -d {target} -o subdomains.txt", "1. Subdomain Enumeration", 30)
    run_cmd("cat subdomains.txt | httpx -silent -o alive.txt -title -web-server -tech-detect", "2. Live Hosts + Tech Detection", 25)
    run_cmd("naabu -list alive.txt -o ports.txt", "3. Port Scanning", 40)
    run_cmd(f"gobuster dir -u https://{target} -w wordlists/directories.txt -o directories.txt -q", "4. Directory Brute Force", 60)
    run_cmd(f"arjun -u https://{target} -o parameters.txt", "5. Parameter Discovery", 45)
    run_cmd(f"ffuf -u https://{target}/FUZZ -w wordlists/directories.txt -o ffuf.json -mc 200,204,301,302 -q", "6. Advanced Fuzzing (ffuf)", 90)
    run_cmd(f"katana -u https://{target} -o endpoints.txt", "7. Crawling", 50)
    run_cmd("nuclei -l alive.txt -severity high,critical,medium -o nuclei_results.txt", "8. Vulnerability Scanning", 300, long_running=True)

    print(Fore.GREEN + "\n🎉 FULL AUTOMATED CHAIN COMPLETED!")
    print(Fore.CYAN + "All major bases covered.")

    if input(Fore.WHITE + "\nGenerate Professional Report now? (y/n): ").lower() == 'y':
        generate_professional_report(target)

def generate_professional_report(target):
    global last_target
    last_target = target
    os.makedirs("reports", exist_ok=True)
    ts = datetime.datetime.now().strftime('%Y%m%d_%H%M')
    filename = f"bugbounty_report_{ts}.md"
    full_path = f"reports/{filename}"

    content = f"""# Bug Bounty Report - {target}

**Date:** {datetime.date.today()}
**Hunter:** [Your Handle]
**Tool:** Termux Bug Bounty Arsenal v2.8
**Target:** {target}

## Full Automated Workflow Completed
- Subdomain Enumeration
- Live Host + Tech Detection
- Port Scanning
- Directory Brute Force
- Parameter Discovery
- Advanced Fuzzing
- Crawling
- Nuclei Vulnerability Scan

## Key Findings
[Review generated files]

## Vulnerabilities
**Title:**  
**Severity:**  
**Description & Steps:**  
**Impact:**  
**Fix:**

---
Generated by the Arsenal
"""
    with open(full_path, "w") as f:
        f.write(content)

    print(Fore.GREEN + "\n" + "="*70)
    print(Fore.GREEN + "✅ PROFESSIONAL REPORT GENERATED!")
    print(Fore.CYAN + f"   📄 {filename}")
    print(Fore.CYAN + f"   📍 reports/{filename}")
    print(Fore.CYAN + "   Open and customize it!")
    print(Fore.GREEN + "="*70)

def main_menu():
    global last_target
    while True:
        banner()
        print(Fore.GREEN + """1. Run ReconX          (Manual)
2. Run CredX           (Manual)
3. Subdomain + Live Hosts
4. Port Scanning
5. Directory Brute Force
6. Nuclei Scan
7. Full Automated Chain (Everything - Recommended)
8. Generate Professional Report
0. Exit""")
        choice = input(Fore.WHITE + "\nChoose → ")

        if choice == "1":
            run_user_tool("reconx/reconx.py", "ReconX")
        elif choice == "2":
            run_user_tool("credx/credx.py", "CredX")
        elif choice == "7":
            full_automated_chain()
        elif choice == "8":
            target = input(f"Target name for report [{last_target}]: ") or last_target
            generate_professional_report(target)
        elif choice == "0":
            print(Fore.RED + "Happy hunting!")
            break
        else:
            print(Fore.YELLOW + "This option is available inside the Full Chain.")

if __name__ == "__main__":
    main_menu()
